devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # importing settings.py file

# help us create url for our static file
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),

]

# grabbed the url and connected it to media root
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),

    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>', views.userProfile, name="user-profile"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile
# Create your models here.


class Project(models.Model):
    # one to many relation ship (one profile many projects)
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    # since this image is in images folder we dont need to specify path for it, eg, if it was in a folder named profile picure then our path would be "profile picture/default.jpg"
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    # you do not need to add the Tag in quote if the Tag model is above the Project model but it is not above the project model in this case so we need to add it within a quote
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    # gives date and a time stamp
    created = models.DateTimeField(auto_now_add=True)
    # auto_now_add=True generates a timestamp whenever a new project entry/model instance is created
    # uuid4 is an encoding type, unique=True means no other value in the database can have the  same number
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    # no need to create an id field whenever we are inheriting from 'models.Model' because django creates it by itself, by default it is of int type
    # but it is recommened to use uuid
    # null=True, blank=True means that the user is able to submit the form even if the field (eg, description) is empty or blank
    # in django, by default null value is False which means the fields should not be left empty

    # anytime we access the model and not it's attribute, it will be output with the title value

    def __str__(self):
        return self.title


class Review(models.Model):
    # VOTE_TYPE is a tuple
    VOTE_TYPE = (
        # we can reference this vote by 'up' in db but 'Up Vote' is what it's gonna be displayed as to the users
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )

    # owner =
    # [on_delete=models.CASCADE] will delete all the reviews if the project is deleted
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.


class Profile(models.Model):
    # user will have one to one rleationship with User model(dajngo's built in model),
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    # every single user in the db will have a profile and every profile will ahve a user and profiel will get automaticlly generated everytime a user is created
    # 'on_delete=models.CASCADE', everytime user is deleted, hs porfile is also deleted
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=500, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        blank=True, null=True, upload_to='profiles/', default='profiles/user-default.png')

    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        # if we want to use a number here then we need to wrap that in a string method (str)
        return str(self.username)


class Skill(models.Model):
    # 'Profile' is the parent and 'Skill' is the child
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm): # 'CustomUserCreationForm(UserCreationForm)' means that CustomUserCreationForm inherist from UserCreationForm
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2' ]
        # modifying how the name of fields will be displyed
        labels = {
            'first_name': 'Name',
        }

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from .models import Profile
from django.contrib import messages
from .forms import CustomUserCreationForm
# Create your views here.


def loginUser(request):
    page = 'login'
    # redirects the user to profile page if he is logged in and he cannot access login page
    if request.user.is_authenticated:
        return redirect('profiles')
    if request.method == "POST":
        # print(request.POST)
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "Username does not exist")

        # takes in the username and password and makes sure that the password matches username and return back either user instance or none
        user = authenticate(request, username=username, password=password)

        # if user exists
        if user is not None:
            # this method will create a session for the user in the db and also add that into the browsers cookies
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, "Username or password was incorrect")
    context = {
        'page': page,
    }
    return render(request, 'users/login_register.html', context)


def logoutUser(request):
    logout(request)  # delete the session
    messages.error(request, "User was logged out")
    return redirect('login')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        # passing the data retrieved from the form
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # creating an instance of the user or the CustomUserCreationForm()
            # 'commit = False' will not save the form right away, it will hold a temporarily instance of it so that we can further make changes to the data retrieved like below then only save it io the db
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()  # finally saving the data to the db

            messages.success(request, 'User account was created!')

            # this method will create a session for the user in the db and also add that into the browsers cookies
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, 'An error has occurred during registration!')
    context = {
        'page': page,
        'form': form,
    }
    return render(request, 'users/login_register.html', context)


def profiles(request):
    profiles = Profile.objects.all()  # getting all the profiles from the db
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):
    # get method gets back a single object
    profile = Profile.objects.get(id=pk)
    # if skill does not have any description or is blank, it will be excluded
    topSkills = profile.skill_set.exclude(description__exact="")
    # if skill has an empty string or blank as a description, it will be selected
    othrtSkills = profile.skill_set.filter(description="")
    context = {'profile': profile,
               'topSkills': topSkills,
               'otherSkills': othrtSkills,
               }
    return render(request, 'users/user-profile.html', context)

templates/users/login_register.html
{% extends 'main.html' %}

{% block content %}
    {% if page == 'register' %}
        <h1>Register User</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <input type="submit" value="Register User">
        </form>
        <p>Already have an account?? <a href="{% url 'login' %}">Sign In</a></p>
    {% else %}
        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Enter Password">
            <input type="submit" value="Login">
            <p>Dont have an account?? <a href="{% url 'register' %}">Sign Up</a></p>
        </form>
    {% endif %}
{% endblock content %}

templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}
    <!-- Main Section -->
    <main class="home">
        <section class="hero-section text-center">
            <div class="container container--narrow">
                <div class="hero-section__box">
                    <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                    <h2>FROM AROUND THE WORLD</h2>
                </div>

                <div class="hero-section__search">
                    <form class="form" action="#" method="get">
                        <div class="form__field">
                            <label for="formInput#search">Search Developers </label>
                            <input class="input input--text" id="formInput#search" type="text" name="text"
                                placeholder="Search by developer name" />
                        </div>

                        <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                    </form>
                </div>
            </div>
        </section>
            <!-- Search Result: DevList -->
            <section class="devlist">
            <div class="container">
                <div class="grid grid--three">

                    {% for profile in profiles %}
                        <div class="column card">
                            <div class="dev">
                                <a href="{%url 'user-profile' profile.id %}" class="card__body">
                                    <div class="dev__profile">
                                        <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                                        <div class="dev__meta">
                                            <h3>{{ profile.name }}</h3>
                                            <h5>{{ profile.short_intro|slice:"60" }}</h5>
                                        </div>
                                    </div>
                                    <p class="dev__info">
                                        {{ profile.bio|slice:"150" }} <!--limiting the total number of words allowed in bio, i.e. 150 -->
                                    </p>
                                    <div class="dev__skills">
                                        {% for skill in profile.skill_set.all|slice:"5" %} <!-- going into all the profile skills-->
                                        <!-- we can get the child objects by adding in child-model-name_set.all-->
                                        <!--Note: child-model-name = Skill 
                                            since child = Skill and 
                                            parent = Profile -->
                                            <span class="tag tag--pill tag--main">
                                                <small>{{ skill }}</small>
                                            </span>
                                        {% endfor %}
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                
                
                </div>
            </div>
        </section>

        <div class="pagination">
        <ul class="container">
            <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
            <li><a href="#" class="btn btn--sub">01</a></li>
            <li><a href="#" class="btn">02</a></li>
            <li><a href="#" class="btn">03</a></li>
            <li><a href="#" class="btn">04</a></li>
            <li><a href="#" class="btn">05</a></li>
            <li><a href="#" class="btn">06</a></li>
            <li><a href="#" class="btn">07</a></li>
            <li><a href="#" class="btn">08</a></li>
            <li><a href="#" class="btn">09</a></li>
            <li><a href="#" class="btn">10</a></li>
            <li><a href="#" class="btn">Next &#10095;</a></li>
        </ul>
        </div>
    </main>
{% endblock content %}

templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
    <!-- Main Section -->
    <main class="profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                    <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
                    <h2 class="dev__name">{{ profile.name }}</h2>
                    <p class="dev__title">{{ profile.short_intro }}</p>
                    <p class="dev__location">Based in {{ profile.location }}</p>
                    <ul class="dev__social">

                        {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{ profile.social_github }}" target="_blank"><!--<i class="im im-github"></i>-->GIT</a>
                            </li>
                        {% endif %}
                        
                        
                        {% if profile.social_twitter %}
                            <li>
                                <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><!--<i class="im im-twitter"></i>-->TWI</a>
                            </li>
                        {% endif %}

                        {% if profile.social_linkedin %}
                            <li>
                                <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><!--<i class="im im-linkedin"></i>-->LIN</a>
                            </li>
                        {% endif %}
                        
                        {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><!--<i class="im im-globe"></i>-->WEB</a>
                            </li>
                        {% endif %}
                    </ul>
                    <a href="#" class="btn btn--sub btn--lg">Send Message </a>
                    </div>
                </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">{{ profile.bio }}</p>
                    </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Skills</h3>
                    <div class="devInfo__skills">
                        {% for skill in topSkills %}
                            <div class="devSkill">
                                <h4 class="devSkill__title">{{ skill.name }}</h4>
                                <p class="devSkill__info">
                                {{ skill.description }}
                                </p>
                            </div>
                        {% endfor %}
                    

                        <h3 class="devInfo__subtitle">Other Skills</h3>
                        <div class="devInfo__otherSkills">
                            {% for skill in otherSkills %}
                                <span class="tag tag--pill tag--sub tag--lg">
                                    <small>{{ skill.name }}</small>
                                </span>
                                {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="devInfo">
                    <h3 class="devInfo__title">Projects</h3>
                    <div class="grid grid--two">
                        {% for project in profile.project_set.all %}
                            <div class="column">
                                <div class="card project">
                                <a href="{% url 'project' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{ project.featured_image.url}}" alt="project thumbnail" />
                                    <div class="card__body">
                                    <h3 class="project__title">{{ project.title }}</h3>
                                    <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{ project.owner.name }}</a></p>
                                    <p class="project--rating">
                                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total| pluralize:"s" }})
                                    </p>
                                    <div class="project__tags">
                                        {% for tag in project.tags.all %} <!--since this a manytomany relationship, we access it this way-->
                                            <span class="tag tag--pill tag--main">
                                                <small>{{ tag }}</small>
                                            </span>
                                        {% endfor %}
                                    </div>
                                    </div>
                                </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}